In [203]:
import numpy as np
import sklearn
import pandas as pd
from sklearn .metrics import roc_auc_score

In [2]:
X = pd.read_csv('training_set_features.csv')

In [3]:
X.set_index('respondent_id' , inplace = True)

In [4]:
X.drop(['hhs_geo_region' , 'census_msa' , 'employment_industry' , 'employment_occupation'], axis = 1 , inplace = True)

In [163]:
# X.head()

In [82]:
X.fillna({ 'xyz_concern' : 2.0} , inplace = True)

In [103]:
X.fillna({ 'xyz_knowledge' : 1.0} , inplace = True)

In [87]:
X.fillna({ 'behavioral_antiviral_meds' : 0.0} , inplace = True)

In [89]:
X.fillna({ 'behavioral_avoidance' : 0.0 }, inplace = True)

In [90]:
X.fillna({ 'behavioral_face_mask' : 0.0} , inplace = True)

In [110]:
X.fillna({ 'behavioral_large_gatherings' : 0.0} , inplace = True)
X.fillna({ 'behavioral_outside_home' : 0.0} , inplace = True)
X.fillna({ 'behavioral_touch_face' : 0.0} , inplace = True)
X.fillna({ 'doctor_recc_xyz' : 0.0} , inplace = True)
X.fillna({ 'doctor_recc_seasonal' : 0.0} , inplace = True)
X.fillna({ 'chronic_med_condition' : 0.0} , inplace = True)
X.fillna({ 'child_under_6_months' : 0.0} , inplace = True)
X.fillna({ 'health_worker' : 0.0} , inplace = True)
X.fillna({ 'health_insurance' : 0.0} , inplace = True)

In [107]:
X.fillna({ 'behavioral_wash_hands' : 0.0} , inplace = True)

In [114]:
X.fillna({ 'opinion_xyz_vacc_effective' : 4.0} , inplace = True)

In [116]:
X.fillna({ 'opinion_xyz_risk' : 2.0} , inplace = True)

In [118]:
X.fillna({ 'opinion_xyz_sick_from_vacc' : 2.0} , inplace = True)

In [120]:
X.fillna({ 'opinion_seas_vacc_effective' : 4.0} , inplace = True)

In [123]:
X.fillna({ 'opinion_seas_risk' : 2.0} , inplace = True)

In [125]:
X.fillna({ 'opinion_seas_sick_from_vacc' : 1.0} , inplace = True)

In [98]:
X.fillna({ 'education' : 'College Graduate'} , inplace = True)

In [99]:
X.fillna({ 'household_children' : 0.0} , inplace = True)

In [126]:
sex_dummy = pd.get_dummies(X.sex , dtype = float )
abc = pd.concat([X , sex_dummy] , axis = 1 )
age_dummy = pd.get_dummies(X.age_group , dtype = float)
education_dummy = pd.get_dummies(X.education , dtype = float)
race_dummy = pd.get_dummies(X.race , dtype = float)
income_poverty_dummy = pd.get_dummies(X.income_poverty , dtype = float)
marital_dummy = pd.get_dummies(X.marital_status , dtype = float)
rent_dummy = pd.get_dummies(X.rent_or_own , dtype = float)
employment_dummy = pd.get_dummies(X.employment_status , dtype = float)
X_upd = pd.concat([abc , age_dummy , education_dummy , race_dummy , income_poverty_dummy , marital_dummy , rent_dummy , employment_dummy] , axis = 1)

In [148]:
X_upd.drop(['sex' , 'age_group' , 'education' , 'race' , 'income_poverty' , 'marital_status' , 'rent_or_own' , 'employment_status'] , axis = 1 , inplace = True)

In [151]:
X_train = X_upd

In [152]:
Y_train = pd.read_csv('training_set_labels.csv')

In [153]:
Y_train.set_index('respondent_id' , inplace = True)

In [154]:
Y_train1 = Y_train['xyz_vaccine']
Y_train2 = Y_train['seasonal_vaccine']

In [216]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
model1 = GaussianNB()
model2 = GaussianNB()

In [217]:
model1.fit(X_train,Y_train1)

GaussianNB()

In [218]:
model2.fit(X_train,Y_train2)

GaussianNB()

In [160]:
X_t = pd.read_csv('test_set_features.csv')

In [240]:
respondent_id = pd.read_csv('test_set_features.csv')

In [161]:
X_t.set_index('respondent_id' , inplace = True)

In [162]:
X_t.drop(['hhs_geo_region' , 'census_msa' , 'employment_industry' , 'employment_occupation'], axis = 1 , inplace = True)

In [164]:
X_t.fillna({ 'xyz_concern' : 2.0} , inplace = True)

In [165]:
X_t.fillna({ 'xyz_knowledge' : 1.0} , inplace = True)

In [166]:
X_t.fillna({ 'behavioral_antiviral_meds' : 0.0} , inplace = True)

In [167]:
X_t.fillna({ 'behavioral_avoidance' : 0.0 }, inplace = True)

In [168]:
X_t.fillna({ 'behavioral_face_mask' : 0.0} , inplace = True)

In [169]:
X_t.fillna({ 'behavioral_large_gatherings' : 0.0} , inplace = True)
X_t.fillna({ 'behavioral_outside_home' : 0.0} , inplace = True)
X_t.fillna({ 'behavioral_touch_face' : 0.0} , inplace = True)
X_t.fillna({ 'doctor_recc_xyz' : 0.0} , inplace = True)
X_t.fillna({ 'doctor_recc_seasonal' : 0.0} , inplace = True)
X_t.fillna({ 'chronic_med_condition' : 0.0} , inplace = True)
X_t.fillna({ 'child_under_6_months' : 0.0} , inplace = True)
X_t.fillna({ 'health_worker' : 0.0} , inplace = True)
X_t.fillna({ 'health_insurance' : 0.0} , inplace = True)

In [176]:
X_t.fillna({ 'household_adults' : 1.0} , inplace = True)

In [185]:
X_t.fillna({ 'income_poverty' : '<= $75,000, Above Poverty'} , inplace = True)
X_t.fillna({ 'marital_status' : 'Married'} , inplace = True)
X_t.fillna({ 'rent_or_own' : 'Own'} , inplace = True)
X_t.fillna({ 'employment_status' : 'Employed'} , inplace = True)

In [170]:
X_t.fillna({ 'behavioral_wash_hands' : 0.0} , inplace = True)
X_t.fillna({ 'opinion_xyz_vacc_effective' : 4.0} , inplace = True)
X_t.fillna({ 'opinion_xyz_risk' : 2.0} , inplace = True)
X_t.fillna({ 'opinion_xyz_sick_from_vacc' : 2.0} , inplace = True)
X_t.fillna({ 'opinion_seas_vacc_effective' : 4.0} , inplace = True)
X_t.fillna({ 'opinion_seas_risk' : 2.0} , inplace = True)
X_t.fillna({ 'opinion_seas_sick_from_vacc' : 1.0} , inplace = True)
X_t.fillna({ 'education' : 'College Graduate'} , inplace = True)
X_t.fillna({ 'household_children' : 0.0} , inplace = True)

In [186]:
sex_dummy1 = pd.get_dummies(X_t.sex , dtype = float )
abc1 = pd.concat([X_t , sex_dummy1] , axis = 1 )
age_dummy1 = pd.get_dummies(X_t.age_group , dtype = float)
education_dummy1 = pd.get_dummies(X_t.education , dtype = float)
race_dummy1 = pd.get_dummies(X_t.race , dtype = float)
income_poverty_dummy1 = pd.get_dummies(X_t.income_poverty , dtype = float)
marital_dummy1 = pd.get_dummies(X_t.marital_status , dtype = float)
rent_dummy1 = pd.get_dummies(X_t.rent_or_own , dtype = float)
employment_dummy1 = pd.get_dummies(X_t.employment_status , dtype = float)
X_upd1 = pd.concat([abc1 , age_dummy1 , education_dummy1 , race_dummy1 , income_poverty_dummy1 , marital_dummy1 , rent_dummy1 , employment_dummy1] , axis = 1)

In [188]:
X_upd1.drop(['sex' , 'age_group' , 'education' , 'race' , 'income_poverty' , 'marital_status' , 'rent_or_own' , 'employment_status'] , axis = 1 , inplace = True)

In [194]:
X_test = X_upd1

In [195]:
model1.predict(X_test)

array([0, 0, 1, ..., 0, 0, 1], dtype=int64)

In [196]:
model2.predict(X_test)

array([0, 0, 1, ..., 0, 1, 1], dtype=int64)

In [220]:
model2.score(X_train,Y_train2)

0.7289474669562287

In [223]:
auc = np.round(roc_auc_score(Y_train1, model1.predict(X_train)), 3)
auc

0.731

In [224]:
model1.predict_proba(X_test[:10])

array([[9.64669148e-01, 3.53308525e-02],
       [9.99981311e-01, 1.86893874e-05],
       [2.91118924e-01, 7.08881067e-01],
       [2.81606949e-01, 7.18393051e-01],
       [8.26718075e-02, 9.17328192e-01],
       [6.16210889e-03, 9.93837891e-01],
       [3.16105395e-01, 6.83894605e-01],
       [9.97883373e-01, 2.11662746e-03],
       [9.99398343e-01, 6.01657006e-04],
       [5.50141577e-01, 4.49858423e-01]])

In [225]:
model2.predict_proba(X_test[:10])

array([[9.99388556e-01, 6.11444043e-04],
       [9.99996454e-01, 3.54565760e-06],
       [2.42418053e-02, 9.75758186e-01],
       [2.72778403e-04, 9.99727222e-01],
       [2.87240143e-01, 7.12759857e-01],
       [6.10776323e-04, 9.99389224e-01],
       [1.09699351e-03, 9.98903006e-01],
       [9.98841208e-01, 1.15879186e-03],
       [8.18005065e-01, 1.81994935e-01],
       [1.16607682e-03, 9.98833923e-01]])

In [236]:
output1 = pd.Series(model1.predict_proba(X_test)[:,1] )
output1

0        0.035331
1        0.000019
2        0.708881
3        0.718393
4        0.917328
           ...   
26703    0.640133
26704    0.105662
26705    0.001043
26706    0.069931
26707    0.666156
Length: 26708, dtype: float64

In [237]:
output2 = pd.Series(model2.predict_proba(X_test)[:,1] )
output2

0        0.000611
1        0.000004
2        0.975758
3        0.999727
4        0.712760
           ...   
26703    0.964256
26704    0.012552
26705    0.000398
26706    0.847009
26707    0.844931
Length: 26708, dtype: float64

In [248]:
output = pd.concat([respondent_id['respondent_id'] ,output1 , output2] , axis =1)
output.columns = ['respondent_id' , 'h1n1_vaccine' , 'seasonal_vaccine']
output.head()

respondent_id  h1n1_vaccine  seasonal_vaccine
0          26707      0.035331          0.000611
1          26708      0.000019          0.000004
2          26709      0.708881          0.975758
3          26710      0.718393          0.999727
4          26711      0.917328          0.712760

In [251]:
output.to_csv('Output.csv')